[config]
model = "gpt-4.1"
fallback_models=["gpt-4o-mini"]
custom_model_max_tokens=128000
duplicate_examples=true

response_language = "zh-CN"
patch_extra_lines_before=4
patch_extra_lines_after=4

patch_extension_skip_types =[".md",".txt", ".json", ".bbmodel"]