name: Build Nightly for Minecraft 1.20.1
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      channel: "nightly"
      branch: "merging/1.20.1-dev"
      publish: true
      kasuga_lib_channel: "nightly"
    secrets:
      KUAYUE_MAVEN_USERNAME: ${{ secrets.KUAYUE_MAVEN_USERNAME }}
      KUAYUE_MAVEN_PASSWORD: ${{ secrets.KUAYUE_MAVEN_PASSWORD }}